#!/bin/bash
# $Id$

PROG=$(basename "$0")
case "$PROG" in
	clang|gcc)
		VAR=cc
		;;
	c++|clang++|g++)
		VAR=cxx
		;;
	*)
		VAR="$PROG"
		;;
esac

echo "$PROG $@" 1>&2
echo "$PROG: Error: You should be using \${configure.$VAR}" 1>&2
echo "See https://trac.macports.org/wiki/UsingTheRightCompiler" 1>&2
exit 1
