#!/bin/bash

# Creates a Makefile that runs "port livecheck" for each port I maintain,
# then runs "make" with multiple simultaneous jobs, then deletes the Makefile.
# The results don't always display in the same order each time, but they do
# come in much faster.

HANDLE=ryandesign
JOBS=8

TMPFILE="$(mktemp "${TMPDIR:=/tmp}/portmylivecheck.XXXXXXXXXX")"

PORTS=$(port echo '(' \
'maintainer:(\s|^)'$HANDLE'(\s|$)' or \
'maintainer:(\s|^)'$HANDLE'@macports.org(\s|$)' or \
'maintainer:(\s|^)macports.org:'$HANDLE'(\s|$)' ')' \
| sed -E 's/ +//g' \
| tr '\n' ' ')

echo "all: $PORTS" > "$TMPFILE"
echo >> "$TMPFILE"
echo ".PHONY: $PORTS" >> "$TMPFILE"

for PORT in $PORTS; do
    echo >> "$TMPFILE"
    echo "$PORT:" >> "$TMPFILE"
    echo $'\t'"port livecheck $PORT" >> "$TMPFILE"
done

make -f "$TMPFILE" -j $JOBS -s || exit $?

rm -f "$TMPFILE"
