#!/bin/bash

# Waits for MacPorts to finish what it's doing, then exits.

PORT="$(which port 2>&1)"

if [ ! -x "$PORT" ]; then
    echo "port command not found" 1>&2
    exit 1
fi

while [ -n "$(ps aww | grep "/usr/bin/tclsh $PORT" | grep -v grep)" ]; do
    sleep 1
done
